### ISSUE TITLE
All tags after august 2022 are pointing to the same commit

### ISSUE THREAD

**Issue by ederuiter** [helium/proto#285]
Given the names of the git tags it would seem the intent is to have a nightly tag/build available; but all tags after august 2022 point to this commit: https://github.com/helium/proto/commit/62fb7e800b0611a810213454b0cd13f29ea609d8

**Comment by madninja** [comment]
Tags are not currently being used for protos outside of the miner build process tagging all the dependent packages. We pick up specific git refs in dependents. Tags will prolly be back as soon as the gateway-rs and oracles code stabilizes
